# Generated by Django 3.2.5 on 2021-08-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doodle_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labels',
            new_name='Label',
        ),
    ]
