# Generated by Django 3.2.5 on 2021-08-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodle_api', '0002_rename_labels_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='image',
            field=models.FileField(upload_to='label_images'),
        ),
    ]
